---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: enear-locker
  title: eNEAR Locker
  tags:
    - contract
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: bridge-team
  type: contract
  lifecycle: production
  system: bridge-connectors
  deployedAt:
    - contract:near/mainnet/e-near.near
  interactsWith:
    - admin:near/mainnet/rainbowbridge.sputnik-dao.near
  subcomponentOf: near-erc20-connector
