---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: enear-locker-on-near
  title: eNEAR Locker on NEAR
  tags:
    - contract
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: bridge-team
  type: contract
  lifecycle: production
  system: bridge-connectors
  deployedAt:
    - contract:near/mainnet/e-near.near
    - contract:near/testnet/enear.goerli.testnet
  interactsWith: []
  subcomponentOf: near-erc20-connector
